Vagrant.configure("2") do |config|
    # configuration of the machine provider
    config.vm.provider "virtualbox" do |v|
        v.cpus = 3
        v.memory = 2048
    end
    
    #copy the configs folder to the guest machine
    config.vm.provision "file", source: "./configs", destination: "~/configs"
  
    # the machines operating system
    config.vm.box = "bento/ubuntu-22.04"

    # MASTER SERVER
    # config.vm.define "ilefhailS" do |master|
    config.vm.hostname = "ilefhailS"
    config.vm.network "private_network",type: "static" ,ip: "192.168.56.110"
    config.vm.provision :shell, path: "scripts/set-up.sh", run: 'always'

        # init commands

    # end
end