Vagrant.configure("2") do |config|
    # configuration of the machine provider
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end
    
    #copy the configs folder to the guest machine
    config.vm.provision "file", source: "./configs", destination: "$HOME/configs"
  
    # the machines operating system
    config.vm.box = "bento/ubuntu-22.04"

    # MASTER SERVER
    config.vm.define "emallahS" do |master|
        master.vm.hostname = "emallahS"
        master.vm.network "private_network", ip: "192.168.56.110", bridge: "eth1"

        # init commands
        master.vm.provision :shell, path: "scripts/set-up.sh", run: 'always'

    end
end