Vagrant.configure("2") do |config|
  
    # configuration of the machine provider
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end
      
    # the machines operating system
    config.vm.box = "bento/ubuntu-22.04"

    # MASTER SERVER
    config.vm.define "emallahS" do |master|
        master.vm.hostname = "emallahS"
        master.vm.network "private_network", ip: "192.168.56.110", bridge: "eth1"

        # init commands
        master.vm.provision :shell, path: "utils/master.sh", run: 'always'

    end

    # SLAVE SERVER
    config.vm.define "emallahSW" do |slave|
        slave.vm.hostname = "emallahSW"
        slave.vm.network "private_network", ip: "192.168.56.111", bridge: "eth1"
        
        # init commands
        slave.vm.provision :shell, path: "utils/slave.sh", run: 'always'
    end

end
